const sidebars = {
	programmesSidebars: [{type: 'autogenerated', dirName: 'programmes'}],
	repetitionsSidebars: [{type: 'autogenerated', dirName: 'repetitions'}],
	chantsSidebars: [{type: 'autogenerated', dirName: 'chants'}],
	eventsSidebars: [{type: 'autogenerated', dirName: 'events'}],
};

export default sidebars;
